### ISSUE TITLE
how to get the target gene list from API?

### ISSUE THREAD

**Issue by KunFang93** [MaayanLab/harmonizome-ml#1]
Hi

Thanks for providing this wonderful database! I wondered if you shed some light on how to access the target genes list for a gene thru API? 
For example, how could I get all 2972 genes list in the attached screenshot?

<img width="1366" alt="Screen Shot 2023-11-20 at 9 11 29 AM" src="https://github.com/MaayanLab/harmonizome-ml/assets/15643651/570b5832-0ef4-4521-808f-5decea062c00">

Thanks for your help!

Best,
Kun

**Comment by u8sand** [comment]
Hi @KunFang93 
![image](https://github.com/MaayanLab/harmonizome-ml/assets/1341861/e5b5a977-f64b-4245-94fb-d031429f85f4)
The button on the left here brings you to the API endpoint you can use, in this case it's
https://maayanlab.cloud/Harmonizome/api/1.0/gene_set/E2F1/ENCODE+Transcription+Factor+Targets

Let us know if you have any further questions.

For example in python
```python
import requests
res = requests.get('https://maayanlab.cloud/Harmonizome/api/1.0/gene_set/E2F1/ENCODE+Transcription+Factor+Targets').json()
print(len(res['associations']))
# 2972
print('\n'.join(r['gene']['symbol'] for r in res['associations']))
# print all the genes line by line
```

**Comment by KunFang93** [comment]
Thank you so much for prompt reply. I have successfully get the genes!

Kun
